import type { IngredientCategory } from '@/types/recipes';

export const ingredientCategoryLabels: Record<IngredientCategory, string> = {
  vegetables: 'Légumes',
  tubers: 'Tubercules',
  fruits: 'Fruits',
  legumes: 'Légumineuses',
  nuts: 'Fruits à coque & graines',
  mushrooms: 'Champignons',
  meat: 'Viandes',
  deli: 'Charcuteries',
  eggs: 'Œufs',
  fish: 'Poissons',
  shellfish: 'Fruits de mer',
  dairy: 'Produits laitiers',
  cereals: 'Céréales & féculents',
  bread: 'Pains',
  oils: 'Huiles',
  fats: 'Matières grasses',
  sweeteners: 'Sucres & édulcorants',
  sweets: 'Sucreries & chocolat',
  pastry: 'Viennoiseries & pâtisseries',
  beverages: 'Boissons',
  alcohol: 'Boissons alcoolisées',
  spices: 'Épices',
  herbs: 'Herbes aromatiques',
  condiments: 'Condiments & sauces',
  plant_proteins: 'Protéines végétales',
  other: 'Autres',
};

export const ingredientCategoryEmojis: Record<IngredientCategory, string> = {
  vegetables: '🥦',
  tubers: '🥔',
  fruits: '🍎',
  legumes: '🫘',
  nuts: '🥜',
  mushrooms: '🍄',
  meat: '🥩',
  deli: '🍖',
  eggs: '🥚',
  fish: '🐟',
  shellfish: '🦐',
  dairy: '🧀',
  cereals: '🌾',
  bread: '🍞',
  oils: '🫙',
  fats: '🧈',
  sweeteners: '🍯',
  sweets: '🍫',
  pastry: '🥐',
  beverages: '🥤',
  alcohol: '🍷',
  spices: '🌶️',
  herbs: '🌿',
  condiments: '🧴',
  plant_proteins: '🌱',
  other: '🛒',
};
